### ISSUE TITLE
Database Synchronization

### ISSUE THREAD

**Issue by GROX13** [AdMove/Android-AdMove#7]
იმ შემთხვევაში თუ მომხმარებელს არ ექნება ინტერნეტთან კავშირი იმ დროს როცა აპლიკაცია იმახსოვრებს მის მოძრაობას, ჩვენ შევინახავთ საჭირო ინფორმაციას ლიკალურად, SQLite მონაცემთა ბაზაში და მხოლოდ მაშინ დავასინქრონიზირებთ ამ ინფორმაციას ამაზონის სერვისთან როდესაც საჭირო ინტერნეტ კავშირი ჩვენთვის ხელმისაწვდომი გახდება.

**Comment by toka16** [comment]
ეს ლოგიკა კოგნიტოს სერვისებში შედის.
